mongodb:
  uri: "mongodb://127.0.0.1:27017"
  database: "wpokt-local"
  timeout_ms: 30000

ethereum:
  start_block_number: 10
  confirmations: 0
  private_key: "ac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
  rpc_url: "https://eth-sepolia.g.alchemy.com/v2/IGe16zdtMuUN1GL-C22TWELlvXRKglia"
  chain_id: "11155111"
  rpc_timeout_ms: 30000
  wrapped_pocket_address: "0x5fbdb2315678afecb367f032d93f642f64180aa3"
  mint_controller_address: "0xe7f1725e7734ce288f8367e1bb143e90bb3f0512"
  validator_addresses:
    - "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
    - "0x70997970C51812dc3A010C7d01b50e0d17dc79C8"
    - "0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC"

pocket:
  start_height: 0
  confirmations: 0
  mnemonic: "infant apart enroll relief kangaroo patch awesome wagon trap feature armor approve"
  rpc_url: "https://shannon-testnet-grove-rpc.beta.poktroll.com"
  rpc_timeout_ms: 5000
  grpc_enabled: false
  grpc_host: 'localhost'
  grpc_port: 9090
  chain_id: "pocket-beta"
  tx_fee: 0
  bech32_prefix: "pokt"
  coin_denom: "upokt"
  multisig_address: "pokt13tsl3aglfyzf02n7x28x2ajzw94muu6y57k2ar"
  multisig_public_keys:
    - "026892de2ec7fdf3125bc1bfd2ff2590d2c9ba756f98a05e9e843ac4d2a1acd4d9"
    - "02faaaf0f385bb17381f36dcd86ab2486e8ff8d93440436496665ac007953076c2"
    - "02cae233806460db75a941a269490ca5165a620b43241edb8bc72e169f4143a6df"
  multisig_threshold: 2

mint_monitor:
  enabled: false
  interval_ms: 1000

mint_signer:
  enabled: false
  interval_ms: 1000

mint_executor:
  enabled: false
  interval_ms: 1000

burn_monitor:
  enabled: false
  interval_ms: 1000

burn_signer:
  enabled: true
  interval_ms: 1000

burn_executor:
  enabled: false
  interval_ms: 1000

health_check:
  interval_ms: 1000
  read_last_health: false

logger:
  level: "debug"

google_secret_manager:
  enabled: false
  mongo_secret_name: ""
  pokt_secret_name: ""
  eth_secret_name: ""
