mongodb:
  uri: "mongodb+srv://<mongodb-user>:<mongodb-password>@<mongodb-host>:<mongodb-port>/<mongodb-database>"
  database: "mongodb-database"
  timeout_ms: 2000

ethereum:
  start_block_number: 0
  confirmations: 0
  private_key: "ac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
  rpc_url: "https://localhost:8545"
  chain_id: "11155111"
  rpc_timeout_ms: 2000
  wrapped_pocket_address: "0xf3cb3c50bc095d7fa15ec5515f849b96cca1ab81"
  mint_controller_address: "0x8ec8384b9cd40f596a609180c9452384d523cf4d"
  validator_addresses:
    - "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
    - "0xE525149C25cc6bF8D743fdc36aAf8BC2EaedFB11"
    - "0xDf79D52a5Cf1aeFf5bC311bAB682283Ee476aA80"

pocket:
  start_height: 0
  confirmations: 0
  mnemonic: "test test test test test test test test test test test junk"
  rpc_url: "http://localhost:26657"
  rpc_timeout_ms: 5000
  grpc_enabled: false
  grpc_host: 'localhost'
  grpc_port: 9090
  chain_id: "poktroll"
  tx_fee: 0
  bech32_prefix: "pokt"
  coin_denom: "upokt"
  multisig_address: "pokt10r5n6x28p9qntchsmhxd4ftq9lk6vzcx3dv4gx"
  multisig_public_keys:
    - "0223aa679d6d5344e201e0df9f02ab15a84726eee0dfb4e953c46a9e2cb52349dc"
    - "02faaaf0f385bb17381f36dcd86ab2486e8ff8d93440436496665ac007953076c2"
    - "02cae233806460db75a941a269490ca5165a620b43241edb8bc72e169f4143a6df"
  multisig_threshold: 2
  mint_disabled: true

mint_monitor:
  enabled: false
  interval_ms: 5000

mint_signer:
  enabled: false
  interval_ms: 5000

mint_executor:
  enabled: false
  interval_ms: 5000

burn_monitor:
  enabled: false
  interval_ms: 5000

burn_signer:
  enabled: false
  interval_ms: 5000

burn_executor:
  enabled: false
  interval_ms: 5000

health_check:
  interval_ms: 5000
  read_last_health: false

logger:
  level: "info"

google_secret_manager:
  enabled: false
  mongo_secret_name: "projects/<project-id>/secrets/<secret-name>/versions/latest"
  pokt_secret_name: "projects/<project-id>/secrets/<secret-name>/versions/latest"
  eth_secret_name: "projects/<project-id>/secrets/<secret-name>/versions/latest"
